name: res-mgmt-rl-dev
channels:
  - pytorch # baseline3
  - conda-forge
dependencies:
  # dev
  - autopep8
  - jupyterlab
  # pytorch dependencies for baseline3
  - cpuonly
  - pytorch
  # for env
  - numpy=1.22
  - pip
  - python=3.10
  - pip:
    - gym
    - pygame
    - stable-baselines3==1.4.0